"""ASCII drawer for the angle-encoding circuit the kernel lane implies.

:mod:`qlab.research.kernels` computes the Gram matrices a product-state
encoding *would* induce, in closed form. No circuit is ever executed, and this
drawing does not claim one is: it is a picture of the feature map behind the
kernel, so a reader of a predictor board can see what ``kernel:zz`` means
without deriving it from :func:`qlab.research.kernels._pair_phases`.

The encoding it draws is the one those kernels are the inner product of: one
wire per feature, ``RY(theta_i)`` with ``theta_i = (pi/2) * unit_i`` from the
unit-scaled feature, and — for the ZZ kernel — an entangler across every
unordered pair ``i < j``, whose phase is ``(pi - theta_i)(pi - theta_j)``.
The pair order here is generated by the same nested loop as ``_pair_phases``,
so the row reads in the column order of the map it depicts.
"""

from __future__ import annotations

import math

from qlab.research.kernels import KERNELS

TITLE = "Quantum kernel circuit (angle encoding)"

# A wider drawing stops being a drawing: twelve wires and their 66 ZZ pairs
# already run past a narrow terminal, and the lane's feature set is smaller.
MAX_WIRES = 12

_DEFAULT_FEATURES = ("x0", "x1", "x2")


def _features(params: dict) -> list[str]:
    raw = params.get("features")
    if raw is None:
        return list(_DEFAULT_FEATURES)
    if isinstance(raw, str) or not isinstance(raw, (list, tuple)):
        raise TypeError("features must be a list of feature names")
    names = [str(name) for name in raw]
    if not names:
        raise ValueError("features must name at least one feature")
    if len(names) > MAX_WIRES:
        raise ValueError(
            f"{len(names)} features exceeds the {MAX_WIRES}-wire drawing "
            "limit; the circuit would not fit a terminal"
        )
    return names


def _angles(params: dict, n_features: int) -> list[float] | None:
    raw = params.get("angles")
    if raw is None:
        return None
    if isinstance(raw, str) or not isinstance(raw, (list, tuple)):
        raise TypeError("angles must be a list of rotation angles in radians")
    if len(raw) != n_features:
        raise ValueError(
            f"angles has {len(raw)} entries for {n_features} features; "
            "one rotation angle per wire is required"
        )
    values = [float(value) for value in raw]
    if not all(math.isfinite(value) for value in values):
        raise ValueError("angles must all be finite")
    return values


def _kernel(params: dict) -> str:
    kind = params.get("kernel") or "angle"
    kind = str(kind)
    if kind not in KERNELS:
        raise ValueError(f"unknown kernel {kind!r}; available: {KERNELS}")
    return kind


def _pairs(names: list[str]) -> list[tuple[str, str]]:
    """The unordered pairs ``_pair_phases`` builds columns for, in its order."""
    return [
        (names[i], names[j])
        for i in range(len(names))
        for j in range(i + 1, len(names))
    ]


def render(params: dict) -> str:
    """Draw the encoding circuit for one predictor run's parameters.

    ``params`` keys, all optional: ``features`` (list of names, default three
    generic wires), ``angles`` (one finite rotation in radians per feature —
    ``(pi/2) * unit_i``; omitted, the gates read ``RY(θi)``), and ``kernel``
    (one of :data:`qlab.research.kernels.KERNELS`, default ``"angle"``).
    """
    if not isinstance(params, dict):
        raise TypeError("params must be a dict")

    names = _features(params)
    angles = _angles(params, len(names))
    kind = _kernel(params)

    gates = [
        f"RY({angles[i]:.2f})" if angles is not None else f"RY(θ{i})"
        for i in range(len(names))
    ]
    label_width = max(len(name) for name in names)
    gate_width = max(len(gate) for gate in gates)

    entangled = kind == "zz" and len(names) > 1
    lines = [
        "angle encoding: one wire per feature, "
        "θi = (π/2) · unit-scaled feature",
        "",
    ]
    for name, gate in zip(names, gates):
        tail = "--*--" if entangled else "-----"
        lines.append(
            f"{name:<{label_width}} |0> --[ {gate:<{gate_width}} ]-{tail}"
        )
    if entangled:
        pairs = " ".join(f"({a},{b})" for a, b in _pairs(names))
        lines.append(f"ZZ entangler, phase (π-θi)(π-θj) over: {pairs}")
    lines.append("")
    caption = f"kernel={kind}  features={len(names)}"
    if kind == "linear":
        caption += "  (linear kernel: the feature map is unused)"
    elif kind == "zz" and len(names) < 2:
        caption += "  (one wire: the ZZ map has no pair and is zero)"
    if angles is None:
        caption += "  (no angles recorded; gates shown symbolically)"
    lines.append(caption)
    return "\n".join(lines)
